version: '3.8'

services:
  svelte:
    container_name: pbrs-fe-dev
    build: 
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "9011:5173"
    volumes:
      - .:/app
      - /app/node_modules  # Prevent overwriting node_modules
    command: ["npm", "run", "dev", "--", "--host"]
    networks:
      - pbrs-network
    environment:
      - VITE_API_URL=http://pbrs-api-gateway:5000  # Use container's internal port
networks:
  pbrs-network:
    external: true
    name: pbrs-network